apiVersion: machine.cmbu.local/v1alpha1
kind: VirtualMachine
metadata:
  name: vm-one
spec:
  description: "Created from a Kubernetes CRD"
  projectId: "90bb3da1-8e1f-40c0-b431-0838e8ebc28d"
  constraints:
  - mandatory: true
    expression: env:vsphere
  flavor: "small"
  tags:
  - key: "custom-tag"
    value: "my-tag-value"
  image: "ubuntu-18"

---
apiVersion: machine.cmbu.local/v1alpha1
kind: VirtualMachine
metadata:
  name: vm-two
spec:
  description: "Created from a Kubernetes CRD"
  projectId: "90bb3da1-8e1f-40c0-b431-0838e8ebc28d"
  constraints:
  - mandatory: true
    expression: env:vsphere
  flavor: "medium"
  tags:
  - key: "custom-tag"
    value: "this-is-vm-two"
  image: "ubuntu-18"

---
apiVersion: machine.cmbu.local/v1alpha1
kind: VirtualMachine
metadata:
  name: vm-three
spec:
  description: "Created from a Kubernetes CRD"
  projectId: "90bb3da1-8e1f-40c0-b431-0838e8ebc28d"
  constraints:
  - mandatory: true
    expression: env:vsphere
  flavor: "small"
  image: "ubuntu-18"

---